[
    {
        "name": "player0",
        "careerSkill": 2080,
        "careerHighestSkill": 1770,
        "careerWins": 260,
        "careerLosses": 100,
        "careerPercent": 72,
        "careerBestLeader": "ZuluShaka",
        "careerAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka"
        ],
        "careerSeasonWins": 210,
        "careerSeasonLosses": 21,
        "careerSeasonPercent": 91,
        "teamSkill": 1780,
        "teamHighestSkill": 1555,
        "teamWins": 210,
        "teamLosses": 10,
        "teamPercent": 95,
        "teamBestLeader": "IndiaGandhi",
        "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
        ],
        "teamSeasonWins": 20,
        "teamSeasonLosses": 2,
        "teamSeasonPercent": 91,
        "duelSkill": 1780,
        "duelHighestSkill": 1900,
        "duelWins": 10,
        "duelLosses": 45,
        "duelPercent": 72,
        "duelBestLeader": "HungaryMatthias",
        "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
        ],
        "duelSeasonWins": 210,
        "duelSeasonLosses": 21,
        "duelSeasonPercent": 91,
        "ffaSkill": 1980,
        "ffaHighestSkill": 1220,
        "ffaWins": 230,
        "ffaLosses": 109,
        "ffaPercent": 67,
        "ffaBestLeader": "MapucheLautaro",
        "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
        ],
        "ffaSeasonWins": 25,
        "ffaSeasonLosses": 54,
        "ffaSeasonPercent": 72,
        "careerHighSkill": 2180,
        "teamHighSkill": 1780,
        "duelHighSkill": 1880,
        "ffaHighSkill": 1980
    },
    {
        "name": "player1",
        "careerSkill": 2080,
        "careerHighestSkill": 1330,
        "careerWins": 78,
        "careerLosses": 80,
        "careerPercent": 49,
        "careerBestLeader": "SwedenKristina",
        "careerAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
        ],
        "careerSeasonWins": 40,
        "careerSeasonLosses": 28,
        "careerSeasonPercent": 59,
        "teamSkill": 1990,
        "teamHighestSkill": 1200,
        "teamWins": 65,
        "teamLosses": 87,
        "teamPercent": 42,
        "teamBestLeader": "KoreaSeondeok",
        "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "teamSeasonWins": 54,
        "teamSeasonLosses": 43,
        "teamSeasonPercent": 56,
        "duelSkill": 1300,
        "duelHighestSkill": 1110,
        "duelWins": 21,
        "duelLosses": 11,
        "duelPercent": 63,
        "duelBestLeader": "AztecMontezuma",
        "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "ChinaQinShiHuang",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SumeriaGilgamesh",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "duelSeasonWins": 34,
        "duelSeasonLosses": 76,
        "duelSeasonPercent": 31,
        "ffaSkill": 1770,
        "ffaHighestSkill": 1990,
        "ffaWins": 90,
        "ffaLosses": 23,
        "ffaPercent": 80,
        "ffaBestLeader": "BrazilPedroII",
        "ffaAllLeader": [
            "SwedenKristina",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "ffaSeasonWins": 22,
        "ffaSeasonLosses": 15,
        "ffaSeasonPercent": 60,
        "careerHighSkill": 2080,
        "teamHighSkill": 1990,
        "duelHighSkill": 1300,
        "ffaHighSkill": 1780
    },
    {
        "name": "player2",
        "careerSkill": 1680,
        "careerHighestSkill": 1511,
        "careerWins": 84,
        "careerLosses": 32,
        "careerPercent": 72,
        "careerBestLeader": "GreeceGorgo",
        "careerAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "careerSeasonWins": 260,
        "careerSeasonLosses": 62,
        "careerSeasonPercent": 80,
        "teamSkill": 1890,
        "teamHighestSkill": 1577,
        "teamWins": 65,
        "teamLosses": 44,
        "teamPercent": 60,
        "teamBestLeader": "ChinaQinShiHuang",
        "teamAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "teamSeasonWins": 203,
        "teamSeasonLosses": 28,
        "teamSeasonPercent": 88,
        "duelSkill": 1580,
        "duelHighestSkill": 1554,
        "duelWins": 10,
        "duelLosses": 21,
        "duelPercent": 32,
        "duelBestLeader": "KongoMvembaANzinga",
        "duelAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "AustraliaJohnCurtin",
            "AustraliaJohnCurtin",
            "AustraliaJohnCurtin",
            "AustraliaJohnCurtin",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "duelSeasonWins": 10,
        "duelSeasonLosses": 32,
        "duelSeasonPercent": 24,
        "ffaSkill": 1550,
        "ffaHighestSkill": 2100,
        "ffaWins": 70,
        "ffaLosses": 59,
        "ffaPercent": 54,
        "ffaBestLeader": "MacedonAlexander",
        "ffaAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "ffaSeasonWins": 43,
        "ffaSeasonLosses": 26,
        "ffaSeasonPercent": 62,
        "careerHighSkill": 1787,
        "teamHighSkill": 1890,
        "duelHighSkill": 1580,
        "ffaHighSkill": 1780
    },
    {
        "name": "player3",
        "careerSkill": 1330,
        "areerHighestSkill": 2000,
        "careerWins": 21,
        "careerLosses": 87,
        "careerPercent": 19,
        "careerBestLeader": "JapanHojoTokimune",
        "careerAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"],
        "careerSeasonWins": 24,
        "careerSeasonLosses": 23,
        "careerSeasonPercent": 51,
        "teamSkill": 1230,
        "teamHighestSkill": 1870,
        "teamWins": 51,
        "teamLosses": 72,
        "teamPercent": 41,
        "teamBestLeader": "KhmerJayavarmanVII",
        "teamAllLeader": [
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "teamSeasonWins": 34,
        "teamSeasonLosses": 68,
        "teamSeasonPercent": 33,
        "duelSkill": 1698,
        "duelHighestSkill": 1280,
        "duelWins": 59,
        "duelLosses": 32,
        "duelPercent": 35,
        "duelBestLeader": "EnglandFranceEleanor",
        "duelAllLeader": [
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "duelSeasonWins": 21,
        "duelSeasonLosses": 78,
        "duelSeasonPercent": 21,
        "ffaSkill": 1400,
        "ffaHighestSkill": 1980,
        "ffaWins": 32,
        "ffaLosses": 89,
        "ffaPercent": 26,
        "ffaBestLeader": "IncaPachacuti",
        "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "ffaSeasonWins": 67,
        "ffaSeasonLosses": 37,
        "ffaSeasonPercent": 64,
        "careerHighSkill": 1330,
        "teamHighSkill": 1230,
        "duelHighSkill": 1720,
        "ffaHighSkill": 1880
    },
    {
        "name": "player4",
        "careerSkill": 1810,
        "careerHighestSkill": 1480,
        "careerWins": 201,
        "careerLosses": 23,
        "careerPercent": 89,
        "careerBestLeader": "GreecePericles",
        "careerAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "careerSeasonWins": 20,
        "careerSeasonLosses": 98,
        "careerSeasonPercent": 17,
        "teamSkill": 1180,
        "teamHighestSkill": 1360,
        "teamWins": 44,
        "teamLosses": 19,
        "teamPercent": 70,
        "teamBestLeader": "HungaryMatthias",
        "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "teamSeasonWins": 76,
        "teamSeasonLosses": 78,
        "teamSeasonPercent": 49,
        "duelSkill": 1710,
        "duelHighestSkill": 1346,
        "duelWins": 111,
        "duelLosses": 157,
        "duelPercent": 41,
        "duelBestLeader": "SumeriaGilgamesh",
        "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "duelSeasonWins": 100,
        "duelSeasonLosses": 200,
        "duelSeasonPercent": 33,
        "ffaSkill": 2010,
        "ffaHighestSkill": 2100,
        "ffaWins": 200,
        "ffaLosses": 100,
        "ffaPercent": 66,
        "ffaBestLeader": "CanadaWilfrid",
        "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "ffaSeasonWins": 26,
        "ffaSeasonLosses": 2,
        "ffaSeasonPercent": 93,
        "careerHighSkill": 1680,
        "teamHighSkill": 1180,
        "duelHighSkill": 1710,
        "ffaHighSkill": 2100
    },
    {
        "name": "player5",
        "careerSkill": 1810,
        "careerHighestSkill": 1760,
        "careerWins": 201,
        "careerLosses": 23,
        "careerPercent": 89,
        "careerBestLeader": "CanadaWilfrid",
        "careerAllLeader": [
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "JapanHojoTokimune",
            "GeorgiaTamar",
            "AustraliaJohnCurtin",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "careerSeasonWins": 20,
        "careerSeasonLosses": 98,
        "careerSeasonPercent": 17,
        "teamSkill": 1180,
        "teamHighestSkill": 1817,
        "teamWins": 44,
        "teamLosses": 19,
        "teamPercent": 70,
        "teamBestLeader": "IndonesiaGitarja",
        "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "teamSeasonWins": 76,
        "teamSeasonLosses": 78,
        "teamSeasonPercent": 49,
        "duelSkill": 1710,
        "highestDuelSkill": 1000,
        "duelWins": 111,
        "duelLosses": 157,
        "duelPercent": 41,
        "duelBestLeader": "IncaPachacuti",
        "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
        ],
        "duelSeasonWins": 100,
        "duelSeasonLosses": 200,
        "duelSeasonPercent": 33,
        "ffaSkill": 2010,
        "ffaHighestSkill": 1251,
        "ffaWins": 200,
        "ffaLosses": 100,
        "ffaPercent": 66,
        "ffaBestLeader": "EnglandVictoria",
        "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
        ],
        "ffaSeasonWins": 26,
        "ffaSeasonLosses": 2,
        "ffaSeasonPercent": 93,
        "careerHighestSkill": 1680,
        "teamHighSkill": 1180,
        "duelHighSkill": 1710,
        "ffaHighSkill": 2100
    }
]