export default 
[
     {
        "name": "player0",
        "careerSkill": 2080,
        "careerHighSkill": 2180,
        "careerWins": 260,
        "careerLosses": 100,
        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "teddy", "teddy"],
        "careerSeasonWins": 210,
        "careerSeasonLosses": 21,

        "teamSkill": 1780,
        "teamHighSkill": 1780,
        "teamWins": 210,
        "teamLosses": 10,
        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "gilgabro"],
        "teamSeasonWins": 20,
        "teamSeasonLosses": 2,

        "duelSkill": 1780,
        "duelHighSkill": 1880,
        "duelWins": 10,
        "duelLosses": 12,
        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "teddy", "teddy"],
        "duelSeasonWins": 210,
        "duelSeasonLosses": 21,

        "ffaSkill": 1980,
        "ffaHighSkill": 1980,
        "ffaWins": 230,
        "ffaLosses": 109,
        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
        "ffaSeasonWins": 25,
        "ffaSeasonLosses": 21
        },
    
        {
        "name": "player1",
        "careerSkill": 2080,
        "careerHighSkill": 2080,
        "careerWins": 78,
        "careerLosses": 80,
        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "gilgabro"],
        "careerSeasonWins": 80,
        "careerSeasonLosses": 28,

        "teamSkill": 1990,
        "teamHighSkill": 1990,
        "teamWins": 65,
        "teamLosses": 87,
        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
        "teamSeasonWins": 54,
        "teamSeasonLosses": 43,

        "duelSkill": 1300,
        "duelHighSkill": 1300,
        "duelWins": 21,
        "duelLosses": 11,
        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
        "duelSeasonWins": 34,
        "duelSeasonLosses": 76,

        "ffaSkill": 1770,
        "ffaHighSkill": 1780,
        "ffaWins": 90,
        "ffaLosses": 23,
        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
        "ffaSeasonWins": 22,
        "ffaSeasonLosses": 15
        },

        {
        "name": "player2",
        "careerSkill": 1680,
        "careerHighSkill": 1787,
        "careerWins": 84,
        "careerLosses": 32,
        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "america", "america", "teddy", "america", "gilgabro"],
        "careerSeasonWins": 92,
        "careerSeasonLosses": 62,

        "teamSkill": 1890,
        "teamHighSkill": 1890,
        "teamWins": 65,
        "teamLosses": 44,
        "teamBestLeader": ["victoria", "america", "america", "america", "america", "teddy", "victoria", "gilgabro", "america"],
        "teamSeasonWins": 203,
        "teamSeasonLosses": 28,

        "duelSkill": 1580,
        "duelHighSkill": 1580,
        "duelWins": 10,
        "duelLosses": 21,
        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "teddy", "victoria", "gilgabro"],
        "duelSeasonWins": 10,
        "duelSeasonLosses": 32,

        "ffaSkill": 1550,
        "ffaHighSkill": 1780,
        "ffaWins": 70,
        "ffaLosses": 59,
        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "germany", "germany", "victoria", "gilgabro"],
        "ffaSeasonWins": 43,
        "ffaSeasonLosses": 26
        },

        {
        "name": "player3",
        "careerSkill": 1330,
        "careerHighSkill": 1330,
        "careerWins": 21,
        "careerLosses": 87,
        "careerBestLeader": ["victoria","gilgabro", "teddy", "gilgabro", "victoria", "gilgabro", "teddy", "victoria", "gilgabro"],
        "careerSeasonWins": 77,
        "careerSeasonLosses": 23,

        "teamSkill": 1230,
        "teamHighSkill": 1230,
        "teamWins": 51,
        "teamLosses": 72,
        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "germany", "germany", "victoria", "gilgabro"],
        "teamSeasonWins": 34,
        "teamSeasonLosses": 68,

        "duelSkill": 1698,
        "duelHighSkill": 1720,
        "duelWins": 59,
        "duelLosses": 32,
        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "germany", "germany", "victoria", "gilgabro", "germany", "germany"],
        "duelSeasonWins": 21,
        "duelSeasonLosses": 78,

        "ffaSkill": 1400,
        "ffaHighSkill": 1880,
        "ffaWins": 32,
        "ffaLosses": 89,
        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "russia", "russia", "russia"],
        "ffaSeasonWins": 67,
        "ffaSeasonLosses": 37
        },

        {
        "name": "player4",
        "careerSkill": 1810,
        "careerHighSkill": 1680,
        "careerWins": 201,
        "careerLosses": 23,
        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "victoria", "victoria", "victoria"],
        "careerSeasonWins": 18,
        "careerSeasonLosses": 98,

        "teamSkill": 1180,
        "teamHighSkill": 1180,
        "teamWins": 44,
        "teamLosses": 19,
        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "teddy", "victoria", "gilgabro","victoria", "teddy", "victoria", "gilgabro", "teddy", "trddy"],
        "teamSeasonWins": 76,
        "teamSeasonLosses": 78,

        "duelSkill": 1710,
        "duelHighSkill": 1710,
        "duelWins": 111,
        "duelLosses": 157,
        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "korea", "korea", "korea", "korea", "korea"],
        "duelSeasonWins": 100,
        "duelSeasonLosses": 200,

        "ffaSkill": 2010,
        "ffaHighSkill": 2100,
        "ffaWins": 200,
        "ffaLosses": 100,
        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gandhi", "gandhi", "gandhi","gandhi"],
        "ffaSeasonWins": 26,
        "ffaSeasonLosses": 2
        },

        {
            "name": "player5",
            "careerSkill": 1810,
            "careerHighSkill": 1680,
            "careerWins": 201,
            "careerLosses": 23,
            "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "victoria", "victoria", "victoria"],
            "careerSeasonWins": 18,
            "careerSeasonLosses": 98,
    
            "teamSkill": 1180,
            "teamHighSkill": 1180,
            "teamWins": 44,
            "teamLosses": 19,
            "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "teddy", "victoria", "gilgabro","victoria", "teddy", "victoria", "gilgabro", "teddy", "trddy"],
            "teamSeasonWins": 76,
            "teamSeasonLosses": 78,
    
            "duelSkill": 1710,
            "duelHighSkill": 1710,
            "duelWins": 111,
            "duelLosses": 157,
            "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "korea", "korea", "korea", "korea", "korea"],
            "duelSeasonWins": 100,
            "duelSeasonLosses": 200,
    
            "ffaSkill": 2010,
            "ffaHighSkill": 2100,
            "ffaWins": 200,
            "ffaLosses": 100,
            "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gandhi", "gandhi", "gandhi","gandhi"],
            "ffaSeasonWins": 26,
            "ffaSeasonLosses": 2
            }
    
]


// [
//     {
//        "name": "player0",
//        "careerSkill": 2080,
//        "careerHighSkill": 2180,
//        "careerWins": 260,
//        "careerLosses": 100,
//        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "teddy", "teddy"],
//        "careerSeasonWins": 210,
//        "careerSeasonLosses": 21,
//        "teamSkill": 1780,
//        "teamHighSkill": 1780,
//        "teamWins": 210,
//        "teamLosses": 10,
//        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "gilgabro"],
//        "teamSeasonWins": 20,
//        "teamSeasonLosses": 2,
//        "duelSkill": 1780,
//        "duelHighSkill": 1880,
//        "duelWins": 10,
//        "duelLosses": 12,
//        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "teddy", "teddy"],
//        "duelSeasonWins": 210,
//        "duelSeasonLosses": 21,
//        "ffaSkill": 1980,
//        "ffaHighSkill": 1980,
//        "ffaWins": 230,
//        "ffaLosses": 109,
//        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
//        "ffaSeasonWins": 25,
//        "ffaSeasonLosses": 21
//        },
//        {
//        "name": "player1",
//        "careerSkill": 2080,
//        "careerHighSkill": 2080,
//        "careerWins": 78,
//        "careerLosses": 80,
//        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "gilgabro"],
//        "careerSeasonWins": 80,
//        "careerSeasonLosses": 28,
//        "teamSkill": 1990,
//        "teamHighSkill": 1990,
//        "teamWins": 65,
//        "teamLosses": 87,
//        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
//        "teamSeasonWins": 54,
//        "teamSeasonLosses": 43,
//        "duelSkill": 1300,
//        "duelHighSkill": 1300,
//        "duelWins": 21,
//        "duelLosses": 11,
//        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
//        "duelSeasonWins": 34,
//        "duelSeasonLosses": 76,
//        "ffaSkill": 1770,
//        "ffaHighSkill": 1780,
//        "ffaWins": 90,
//        "ffaLosses": 23,
//        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro"],
//        "ffaSeasonWins": 22,
//        "ffaSeasonLosses": 15
//        },
//        {
//        "name": "player2",
//        "careerSkill": 1680,
//        "careerHighSkill": 1787,
//        "careerWins": 84,
//        "careerLosses": 32,
//        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "america", "america", "teddy", "america", "gilgabro"],
//        "careerSeasonWins": 92,
//        "careerSeasonLosses": 62,
//        "teamSkill": 1890,
//        "teamHighSkill": 1890,
//        "teamWins": 65,
//        "teamLosses": 44,
//        "teamBestLeader": ["victoria", "america", "america", "america", "america", "teddy", "victoria", "gilgabro", "america"],
//        "teamSeasonWins": 203,
//        "teamSeasonLosses": 28,
//        "duelSkill": 1580,
//        "duelHighSkill": 1580,
//        "duelWins": 10,
//        "duelLosses": 21,
//        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "teddy", "victoria", "gilgabro"],
//        "duelSeasonWins": 10,
//        "duelSeasonLosses": 32,
//        "ffaSkill": 1550,
//        "ffaHighSkill": 1780,
//        "ffaWins": 70,
//        "ffaLosses": 59,
//        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "germany", "germany", "victoria", "gilgabro"],
//        "ffaSeasonWins": 43,
//        "ffaSeasonLosses": 26
//        },
//        {
//        "name": "player3",
//        "careerSkill": 1330,
//        "careerHighSkill": 1330,
//        "careerWins": 21,
//        "careerLosses": 87,
//        "careerBestLeader": ["victoria","gilgabro", "teddy", "gilgabro", "victoria", "gilgabro", "teddy", "victoria", "gilgabro"],
//        "careerSeasonWins": 77,
//        "careerSeasonLosses": 23,
//        "teamSkill": 1230,
//        "teamHighSkill": 1230,
//        "teamWins": 51,
//        "teamLosses": 72,
//        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gilgabro", "germany", "germany", "victoria", "gilgabro"],
//        "teamSeasonWins": 34,
//        "teamSeasonLosses": 68,
//        "duelSkill": 1698,
//        "duelHighSkill": 1720,
//        "duelWins": 59,
//        "duelLosses": 32,
//        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "germany", "germany", "victoria", "gilgabro", "germany", "germany"],
//        "duelSeasonWins": 21,
//        "duelSeasonLosses": 78,
//        "ffaSkill": 1400,
//        "ffaHighSkill": 1880,
//        "ffaWins": 32,
//        "ffaLosses": 89,
//        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "russia", "russia", "russia"],
//        "ffaSeasonWins": 67,
//        "ffaSeasonLosses": 37
//        },
//        {
//        "name": "player4",
//        "careerSkill": 1810,
//        "careerHighSkill": 1680,
//        "careerWins": 201,
//        "careerLosses": 23,
//        "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "victoria", "victoria", "victoria"],
//        "careerSeasonWins": 18,
//        "careerSeasonLosses": 98,
//        "teamSkill": 1180,
//        "teamHighSkill": 1180,
//        "teamWins": 44,
//        "teamLosses": 19,
//        "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "teddy", "victoria", "gilgabro","victoria", "teddy", "victoria", "gilgabro", "teddy", "trddy"],
//        "teamSeasonWins": 76,
//        "teamSeasonLosses": 78,
//        "duelSkill": 1710,
//        "duelHighSkill": 1710,
//        "duelWins": 111,
//        "duelLosses": 157,
//        "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "korea", "korea", "korea", "korea", "korea"],
//        "duelSeasonWins": 100,
//        "duelSeasonLosses": 200,
//        "ffaSkill": 2010,
//        "ffaHighSkill": 2100,
//        "ffaWins": 200,
//        "ffaLosses": 100,
//        "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gandhi", "gandhi", "gandhi","gandhi"],
//        "ffaSeasonWins": 26,
//        "ffaSeasonLosses": 2
//        },
//        {
//            "name": "player5",
//            "careerSkill": 1810,
//            "careerHighSkill": 1680,
//            "careerWins": 201,
//            "careerLosses": 23,
//            "careerBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "victoria", "victoria", "victoria"],
//            "careerSeasonWins": 18,
//            "careerSeasonLosses": 98,
//            "teamSkill": 1180,
//            "teamHighSkill": 1180,
//            "teamWins": 44,
//            "teamLosses": 19,
//            "teamBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "victoria", "teddy", "victoria", "gilgabro","victoria", "teddy", "victoria", "gilgabro", "teddy", "trddy"],
//            "teamSeasonWins": 76,
//            "teamSeasonLosses": 78,  
//            "duelSkill": 1710,
//            "duelHighSkill": 1710,
//            "duelWins": 111,
//            "duelLosses": 157,
//            "duelBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "korea", "korea", "korea", "korea", "korea"],
//            "duelSeasonWins": 100,
//            "duelSeasonLosses": 200,
//            "ffaSkill": 2010,
//            "ffaHighSkill": 2100,
//            "ffaWins": 200,
//            "ffaLosses": 100,
//            "ffaBestLeader": ["victoria", "teddy", "victoria", "gilgabro", "gandhi", "gandhi", "gandhi","gandhi"],
//            "ffaSeasonWins": 26,
//            "ffaSeasonLosses": 2
//            }
// ]

