import React, { Component } from 'react';
import { Redirect } from 'react-router';
import Navbar from '../Navbar/Navbar';
import glicko2 from 'glicko2';

class Newsletters extends Component {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
    var settings = {
      tau: 0.2,
      rating: 1500,
      rd: 250,
      vol: 0.06
    };

    var ranking = new glicko2.Glicko2(settings);

    var gameType = 'duel'
    //var updatedStats = allPlayerStats.slice();

    const allPlayerStats = [
      [
        {
          "name": "player0",
          "careerSkill": 2080,
          "careerHighestSkill": 1500,
          "careerWins": 260,
          "careerLosses": 100,
          "careerPercent": 72,
          "careerBestLeader": "ZuluShaka",
          "careerAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka"
          ],
          "id": 3,
          "highestCareerSkill": 1770,
          "careerSeasonWins": 210,
          "careerSeasonLosses": 21,
          "careerSeasonPercent": 91,
          "teamSkill": 1780,
          "highestTeamSkill": 1500,
          "teamWins": 210,
          "teamLosses": 10,
          "teamPercent": 95,
          "teamBestLeader": "IndiaGandhi",
          "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
          ],
          "teamSeasonWins": 20,
          "teamSeasonLosses": 2,
          "teamSeasonPercent": 91,
          "duelSkill": 1780,
          "highestDuelSkill": 1500,
          "duelWins": 10,
          "duelLosses": 45,
          "duelPercent": 72,
          "duelBestLeader": "HungaryMatthias",
          "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
          ],
          "duelSeasonWins": 210,
          "duelSeasonLosses": 21,
          "duelSeasonPercent": 91,
          "ffaSkill": 1980,
          "highestffaSkill": 1500,
          "ffaWins": 230,
          "ffaLosses": 109,
          "ffaPercent": 67,
          "ffaBestLeader": "MapucheLautaro",
          "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
          ],
          "ffaSeasonWins": 25,
          "ffaSeasonLosses": 54,
          "ffaSeasonPercent": 72,
          "careerHighSkill": 2180,
          "teamHighSkill": 1780,
          "duelHighSkill": 1880,
          "ffaHighSkill": 1980
        },
        false
      ],
      [
        {
          "name": "player1",
          "careerSkill": 2080,
          "careerHighestSkill": 1500,
          "careerWins": 78,
          "careerLosses": 80,
          "careerPercent": 49,
          "careerBestLeader": "SwedenKristina",
          "careerAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
          ],
          "id": 4,
          "highestCareerSkill": 1330,
          "careerSeasonWins": 40,
          "careerSeasonLosses": 28,
          "careerSeasonPercent": 59,
          "teamSkill": 1990,
          "highestTeamSkill": 1500,
          "teamWins": 65,
          "teamLosses": 87,
          "teamPercent": 42,
          "teamBestLeader": "KoreaSeondeok",
          "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "teamSeasonWins": 54,
          "teamSeasonLosses": 43,
          "teamSeasonPercent": 56,
          "duelSkill": 1300,
          "highestDuelSkill": 1500,
          "duelWins": 21,
          "duelLosses": 11,
          "duelPercent": 63,
          "duelBestLeader": "AztecMontezuma",
          "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "ChinaQinShiHuang",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SumeriaGilgamesh",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "duelSeasonWins": 34,
          "duelSeasonLosses": 76,
          "duelSeasonPercent": 31,
          "ffaSkill": 1770,
          "highestffaSkill": 1500,
          "ffaWins": 90,
          "ffaLosses": 23,
          "ffaPercent": 80,
          "ffaBestLeader": "BrazilPedroII",
          "ffaAllLeader": [
            "SwedenKristina",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "ffaSeasonWins": 22,
          "ffaSeasonLosses": 15,
          "ffaSeasonPercent": 60,
          "careerHighSkill": 2080,
          "teamHighSkill": 1990,
          "duelHighSkill": 1300,
          "ffaHighSkill": 1780
        },
        false
      ],
      [
        {
          "name": "player2",
          "careerSkill": 1680,
          "careerHighestSkill": 1500,
          "careerWins": 84,
          "careerLosses": 32,
          "careerPercent": 72,
          "careerBestLeader": "GreeceGorgo",
          "careerAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "id": 9,
          "highestCareerSkill": 1760,
          "careerSeasonWins": 260,
          "careerSeasonLosses": 62,
          "careerSeasonPercent": 80,
          "teamSkill": 1890,
          "highestTeamSkill": 1500,
          "teamWins": 65,
          "teamLosses": 44,
          "teamPercent": 60,
          "teamBestLeader": "ChinaQinShiHuang",
          "teamAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "teamSeasonWins": 203,
          "teamSeasonLosses": 28,
          "teamSeasonPercent": 88,
          "duelSkill": 1580,
          "highestDuelSkill": 1500,
          "duelWins": 10,
          "duelLosses": 21,
          "duelPercent": 32,
          "duelBestLeader": "KongoMvembaANzinga",
          "duelAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "AustraliaJohnCurtin",
            "AustraliaJohnCurtin",
            "AustraliaJohnCurtin",
            "AustraliaJohnCurtin",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "duelSeasonWins": 10,
          "duelSeasonLosses": 32,
          "duelSeasonPercent": 24,
          "ffaSkill": 1550,
          "highestffaSkill": 1500,
          "ffaWins": 70,
          "ffaLosses": 59,
          "ffaPercent": 54,
          "ffaBestLeader": "MacedonAlexander",
          "ffaAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "ffaSeasonWins": 43,
          "ffaSeasonLosses": 26,
          "ffaSeasonPercent": 62,
          "careerHighSkill": 1787,
          "teamHighSkill": 1890,
          "duelHighSkill": 1580,
          "ffaHighSkill": 1780
        },
        false
      ],
      [
        {
          "name": "player3",
          "careerSkill": 1330,
          "careerHighestSkill": 1500,
          "careerWins": 21,
          "careerLosses": 87,
          "careerPercent": 19,
          "careerBestLeader": "JapanHojoTokimune",
          "careerAllLeader": [
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "id": 6,
          "highestCareerSkill": 1511,
          "careerSeasonWins": 24,
          "careerSeasonLosses": 23,
          "careerSeasonPercent": 51,
          "teamSkill": 1230,
          "highestTeamSkill": 1500,
          "teamWins": 51,
          "teamLosses": 72,
          "teamPercent": 41,
          "teamBestLeader": "KhmerJayavarmanVII",
          "teamAllLeader": [
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "teamSeasonWins": 34,
          "teamSeasonLosses": 68,
          "teamSeasonPercent": 33,
          "duelSkill": 1698,
          "highestDuelSkill": 1500,
          "duelWins": 59,
          "duelLosses": 32,
          "duelPercent": 35,
          "duelBestLeader": "EnglandFranceEleanor",
          "duelAllLeader": [
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "duelSeasonWins": 21,
          "duelSeasonLosses": 78,
          "duelSeasonPercent": 21,
          "ffaSkill": 1400,
          "highestffaSkill": 1500,
          "ffaWins": 32,
          "ffaLosses": 89,
          "ffaPercent": 26,
          "ffaBestLeader": "IncaPachacuti",
          "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "ffaSeasonWins": 67,
          "ffaSeasonLosses": 37,
          "ffaSeasonPercent": 64,
          "careerHighSkill": 1330,
          "teamHighSkill": 1230,
          "duelHighSkill": 1720,
          "ffaHighSkill": 1880
        },
        false
      ],
      [
        {
          "name": "player4",
          "careerSkill": 1810,
          "careerHighestSkill": 1500,
          "careerWins": 201,
          "careerLosses": 23,
          "careerPercent": 89,
          "careerBestLeader": "GreecePericles",
          "careerAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "id": 7,
          "highestCareerSkill": 1480,
          "careerSeasonWins": 20,
          "careerSeasonLosses": 98,
          "careerSeasonPercent": 17,
          "teamSkill": 1180,
          "highestTeamSkill": 1500,
          "teamWins": 44,
          "teamLosses": 19,
          "teamPercent": 70,
          "teamBestLeader": "HungaryMatthias",
          "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "teamSeasonWins": 76,
          "teamSeasonLosses": 78,
          "teamSeasonPercent": 49,
          "duelSkill": 1710,
          "highestDuelSkill": 1500,
          "duelWins": 111,
          "duelLosses": 157,
          "duelPercent": 41,
          "duelBestLeader": "SumeriaGilgamesh",
          "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "duelSeasonWins": 100,
          "duelSeasonLosses": 200,
          "duelSeasonPercent": 33,
          "ffaSkill": 2010,
          "highestffaSkill": 1500,
          "ffaWins": 200,
          "ffaLosses": 100,
          "ffaPercent": 66,
          "ffaBestLeader": "CanadaWilfrid",
          "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "ffaSeasonWins": 26,
          "ffaSeasonLosses": 2,
          "ffaSeasonPercent": 93,
          "careerHighSkill": 1680,
          "teamHighSkill": 1180,
          "duelHighSkill": 1710,
          "ffaHighSkill": 2100
        },
        false
      ],
      [
        {
          "name": "player5",
          "careerSkill": 1810,
          "careerHighestSkill": 1500,
          "careerWins": 201,
          "careerLosses": 23,
          "careerPercent": 89,
          "careerBestLeader": "CanadaWilfrid",
          "careerAllLeader": [
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "JapanHojoTokimune",
            "AustraliaJohnCurtin",
            "HungaryMatthias",
            "GreecePericles",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "JapanHojoTokimune",
            "GeorgiaTamar",
            "AustraliaJohnCurtin",
            "IndonesiaGitarja",
            "AustraliaJohnCurtin",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "id": 8,
          "highestCareerSkill": 1760,
          "careerSeasonWins": 20,
          "careerSeasonLosses": 98,
          "careerSeasonPercent": 17,
          "teamSkill": 1180,
          "highestTeamSkill": 1500,
          "teamWins": 44,
          "teamLosses": 19,
          "teamPercent": 70,
          "teamBestLeader": "IndonesiaGitarja",
          "teamAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "IndonesiaGitarja",
            "IndiaGandhi",
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "SwedenKristina",
            "SumeriaGilgamesh",
            "ZuluShaka",
            "MapucheLautaro",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "GeorgiaTamar",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "teamSeasonWins": 76,
          "teamSeasonLosses": 78,
          "teamSeasonPercent": 49,
          "duelSkill": 1710,
          "highestDuelSkill": 1500,
          "duelWins": 111,
          "duelLosses": 157,
          "duelPercent": 41,
          "duelBestLeader": "IncaPachacuti",
          "duelAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo"
          ],
          "duelSeasonWins": 100,
          "duelSeasonLosses": 200,
          "duelSeasonPercent": 33,
          "ffaSkill": 2010,
          "highestffaSkill": 1500,
          "ffaWins": 200,
          "ffaLosses": 100,
          "ffaPercent": 66,
          "ffaBestLeader": "EnglandVictoria",
          "ffaAllLeader": [
            "ZuluShaka",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "SwedenKristina",
            "GeorgiaTamar",
            "SumeriaGilgamesh",
            "FranceCatherinedeMedici",
            "EnglandVictoria",
            "EnglandFranceEleanor",
            "EgyptCleopatra",
            "DutchWilhelmina",
            "CreePoundmaker",
            "ChinaQinShiHuang",
            "CanadaWilfrid",
            "BrazilPedroII",
            "AztecMontezuma",
            "MaoriKupe",
            "MaliMansa",
            "MacedonAlexander",
            "KoreaSeondeok",
            "KongoMvembaANzinga",
            "KhmerJayavarmanVII",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "IncaPachacuti",
            "JapanHojoTokimune",
            "IndiaGandhi",
            "IndiaChandragupta",
            "IncaPachacuti",
            "HungaryMatthias",
            "GreecePericles",
            "GreeceGorgo",
            "GermanyFrederickBarbarossa",
            "GermanyFrederickBarbarossa"
          ],
          "ffaSeasonWins": 26,
          "ffaSeasonLosses": 2,
          "ffaSeasonPercent": 93,
          "careerHighSkill": 1680,
          "teamHighSkill": 1180,
          "duelHighSkill": 1710,
          "ffaHighSkill": 2100
        },
        false
      ],
      [
        {
          "name": "player6",
          "careerSkill": 1500,
          "careerHighestSkill": 1500,
          "careerWins": 0,
          "careerLosses": 0,
          "careerPercent": 0,
          "careerBestLeader": "none",
          "careerAllLeader": [
            "none"
          ],
          "id": 33,
          "highestCareerSkill": 1500,
          "careerSeasonWins": 0,
          "careerSeasonLosses": 0,
          "careerSeasonPercent": 0,
          "teamSkill": 1500,
          "highestTeamSkill": 1500,
          "teamWins": 0,
          "teamLosses": 0,
          "teamPercent": 0,
          "teamBestLeader": "none",
          "teamAllLeader": [
            "none"
          ],
          "teamSeasonWins": 0,
          "teamSeasonLosses": 0,
          "teamSeasonPercent": 0,
          "duelSkill": 1500,
          "highestDuelSkill": 1500,
          "duelWins": 0,
          "duelLosses": 0,
          "duelPercent": 0,
          "duelBestLeader": "none",
          "duelAllLeader": [
            "none"
          ],
          "duelSeasonWins": 0,
          "duelSeasonLosses": 0,
          "duelSeasonPercent": 0,
          "ffaSkill": 1500,
          "highestffaSkill": 1500,
          "ffaWins": 1500,
          "ffaLosses": 0,
          "ffaPercent": 0,
          "ffaBestLeader": "none",
          "ffaAllLeader": [
            "none"
          ],
          "ffaSeasonWins": 0,
          "ffaSeasonLosses": 0,
          "ffaSeasonPercent": 0,
          "careerHighSkill": 1500,
          "teamHighSkill": 1500,
          "duelHighSkill": 1500,
          "ffaHighSkill": 1500
        },
        false
      ],
      [
        {
          "name": "player30",
          "careerSkill": 1500,
          "careerHighestSkill": 1500,
          "careerWins": 0,
          "careerLosses": 0,
          "careerPercent": 0,
          "careerBestLeader": "none",
          "careerAllLeader": [
            "none"
          ],
          "id": 28,
          "highestCareerSkill": 1500,
          "careerSeasonWins": 0,
          "careerSeasonLosses": 0,
          "careerSeasonPercent": 0,
          "teamSkill": 1500,
          "highestTeamSkill": 1500,
          "teamWins": 0,
          "teamLosses": 0,
          "teamPercent": 0,
          "teamBestLeader": "none",
          "teamAllLeader": [
            "none"
          ],
          "teamSeasonWins": 0,
          "teamSeasonLosses": 0,
          "teamSeasonPercent": 0,
          "duelSkill": 1500,
          "highestDuelSkill": 1500,
          "duelWins": 0,
          "duelLosses": 0,
          "duelPercent": 0,
          "duelBestLeader": "none",
          "duelAllLeader": [
            "none"
          ],
          "duelSeasonWins": 0,
          "duelSeasonLosses": 0,
          "duelSeasonPercent": 0,
          "ffaSkill": 1500,
          "highestffaSkill": 1500,
          "ffaWins": 1500,
          "ffaLosses": 0,
          "ffaPercent": 0,
          "ffaBestLeader": "none",
          "ffaAllLeader": [
            "none"
          ],
          "ffaSeasonWins": 0,
          "ffaSeasonLosses": 0,
          "ffaSeasonPercent": 0,
          "careerHighSkill": 1500,
          "teamHighSkill": 1500,
          "duelHighSkill": 1500,
          "ffaHighSkill": 1500
        },
        false
      ],
      [
        {
          "name": "player31",
          "careerSkill": 1500,
          "careerHighestSkill": 1500,
          "careerWins": 0,
          "careerLosses": 0,
          "careerPercent": 0,
          "careerBestLeader": "none",
          "careerAllLeader": [
            "none"
          ],
          "id": 29,
          "highestCareerSkill": 1500,
          "careerSeasonWins": 0,
          "careerSeasonLosses": 0,
          "careerSeasonPercent": 0,
          "teamSkill": 1500,
          "highestTeamSkill": 1500,
          "teamWins": 0,
          "teamLosses": 0,
          "teamPercent": 0,
          "teamBestLeader": "none",
          "teamAllLeader": [
            "none"
          ],
          "teamSeasonWins": 0,
          "teamSeasonLosses": 0,
          "teamSeasonPercent": 0,
          "duelSkill": 1500,
          "highestDuelSkill": 1500,
          "duelWins": 0,
          "duelLosses": 0,
          "duelPercent": 0,
          "duelBestLeader": "none",
          "duelAllLeader": [
            "none"
          ],
          "duelSeasonWins": 0,
          "duelSeasonLosses": 0,
          "duelSeasonPercent": 0,
          "ffaSkill": 1500,
          "highestffaSkill": 1500,
          "ffaWins": 1500,
          "ffaLosses": 0,
          "ffaPercent": 0,
          "ffaBestLeader": "none",
          "ffaAllLeader": [
            "none"
          ],
          "ffaSeasonWins": 0,
          "ffaSeasonLosses": 0,
          "ffaSeasonPercent": 0,
          "careerHighSkill": 1500,
          "teamHighSkill": 1500,
          "duelHighSkill": 1500,
          "ffaHighSkill": 1500
        },
        false
      ],
      [
        {
          "name": "player32",
          "careerSkill": 1500,
          "careerHighestSkill": 1500,
          "careerWins": 0,
          "careerLosses": 0,
          "careerPercent": 0,
          "careerBestLeader": "none",
          "careerAllLeader": [
            "none"
          ],
          "id": 30,
          "highestCareerSkill": 1500,
          "careerSeasonWins": 0,
          "careerSeasonLosses": 0,
          "careerSeasonPercent": 0,
          "teamSkill": 1500,
          "highestTeamSkill": 1500,
          "teamWins": 0,
          "teamLosses": 0,
          "teamPercent": 0,
          "teamBestLeader": "none",
          "teamAllLeader": [
            "none"
          ],
          "teamSeasonWins": 0,
          "teamSeasonLosses": 0,
          "teamSeasonPercent": 0,
          "duelSkill": 1500,
          "highestDuelSkill": 1500,
          "duelWins": 0,
          "duelLosses": 0,
          "duelPercent": 0,
          "duelBestLeader": "none",
          "duelAllLeader": [
            "none"
          ],
          "duelSeasonWins": 0,
          "duelSeasonLosses": 0,
          "duelSeasonPercent": 0,
          "ffaSkill": 1500,
          "highestffaSkill": 1500,
          "ffaWins": 1500,
          "ffaLosses": 0,
          "ffaPercent": 0,
          "ffaBestLeader": "none",
          "ffaAllLeader": [
            "none"
          ],
          "ffaSeasonWins": 0,
          "ffaSeasonLosses": 0,
          "ffaSeasonPercent": 0,
          "careerHighSkill": 1500,
          "teamHighSkill": 1500,
          "duelHighSkill": 1500,
          "ffaHighSkill": 1500
        },
        false
      ],
      [
        {
          "name": "player33",
          "careerSkill": 1500,
          "careerHighestSkill": 1500,
          "careerWins": 0,
          "careerLosses": 0,
          "careerPercent": 0,
          "careerBestLeader": "none",
          "careerAllLeader": [
            "none"
          ],
          "id": 31,
          "highestCareerSkill": 1500,
          "careerSeasonWins": 0,
          "careerSeasonLosses": 0,
          "careerSeasonPercent": 0,
          "teamSkill": 1500,
          "highestTeamSkill": 1500,
          "teamWins": 0,
          "teamLosses": 0,
          "teamPercent": 0,
          "teamBestLeader": "none",
          "teamAllLeader": [
            "none"
          ],
          "teamSeasonWins": 0,
          "teamSeasonLosses": 0,
          "teamSeasonPercent": 0,
          "duelSkill": 1500,
          "highestDuelSkill": 1500,
          "duelWins": 0,
          "duelLosses": 0,
          "duelPercent": 0,
          "duelBestLeader": "none",
          "duelAllLeader": [
            "none"
          ],
          "duelSeasonWins": 0,
          "duelSeasonLosses": 0,
          "duelSeasonPercent": 0,
          "ffaSkill": 1500,
          "highestffaSkill": 1500,
          "ffaWins": 1500,
          "ffaLosses": 0,
          "ffaPercent": 0,
          "ffaBestLeader": "none",
          "ffaAllLeader": [
            "none"
          ],
          "ffaSeasonWins": 0,
          "ffaSeasonLosses": 0,
          "ffaSeasonPercent": 0,
          "careerHighSkill": 1500,
          "teamHighSkill": 1500,
          "duelHighSkill": 1500,
          "ffaHighSkill": 1500
        },
        false
      ],
      [
        {
          "name": "player34",
          "careerSkill": 1500,
          "careerHighestSkill": 1500,
          "careerWins": 0,
          "careerLosses": 0,
          "careerPercent": 0,
          "careerBestLeader": "none",
          "careerAllLeader": [
            "none"
          ],
          "id": 32,
          "highestCareerSkill": 1500,
          "careerSeasonWins": 0,
          "careerSeasonLosses": 0,
          "careerSeasonPercent": 0,
          "teamSkill": 1500,
          "highestTeamSkill": 1500,
          "teamWins": 0,
          "teamLosses": 0,
          "teamPercent": 0,
          "teamBestLeader": "none",
          "teamAllLeader": [
            "none"
          ],
          "teamSeasonWins": 0,
          "teamSeasonLosses": 0,
          "teamSeasonPercent": 0,
          "duelSkill": 1500,
          "highestDuelSkill": 1500,
          "duelWins": 0,
          "duelLosses": 0,
          "duelPercent": 0,
          "duelBestLeader": "none",
          "duelAllLeader": [
            "none"
          ],
          "duelSeasonWins": 0,
          "duelSeasonLosses": 0,
          "duelSeasonPercent": 0,
          "ffaSkill": 1500,
          "highestffaSkill": 1500,
          "ffaWins": 1500,
          "ffaLosses": 0,
          "ffaPercent": 0,
          "ffaBestLeader": "none",
          "ffaAllLeader": [
            "none"
          ],
          "ffaSeasonWins": 0,
          "ffaSeasonLosses": 0,
          "ffaSeasonPercent": 0,
          "careerHighSkill": 1500,
          "teamHighSkill": 1500,
          "duelHighSkill": 1500,
          "ffaHighSkill": 1500
        },
        false
      ]
    ];
    if (gameType === 'ffa') {
      makeTheFfaPlayers();
      function makeTheFfaPlayers() {
        const madePlayers = [];
        allPlayerStats.map((playerName, i) => {
          var onePlayersStats = {
            user: playerName[0].name, value: ranking.makePlayer(playerName[0].ffaSkill, playerName[0].ffaRatingDiviation, playerName[0].ffaVolatility)
          }
          madePlayers.push(onePlayersStats)
        });
        evaluate(madePlayers)
      }

      makeTheFfaSeasonPlayers();
      function makeTheFfaSeasonPlayers() {
        const madePlayers = [];
        allPlayerStats.map((playerName, i) => {
          var onePlayersStats = {
            user: playerName[0].name, value: ranking.makePlayer(playerName[0].ffaSeasonSkill, playerName[0].ffaSeasonRatingDiviation, playerName[0].ffaSeasonVolatility)
          }
          madePlayers.push(onePlayersStats)
        });
        evaluate(madePlayers)
      }
    }

    if (gameType === 'team') {
      makeTheTeaamPlayers();
      function makeTheTeaamPlayers() {
        const madePlayers = [];
        allPlayerStats.map((playerName, i) => {
          var onePlayersStats = {
            user: playerName[0].name, value: ranking.makePlayer(playerName[0].teamSkill, playerName[0].teamRatingDiviation, playerName[0].teamVolatility)
          }
          madePlayers.push(onePlayersStats)
        });
        evaluate(madePlayers)
      }

      makeTheTeamSeasonPlayers();
      function makeTheTeamSeasonPlayers() {
        const madePlayers = [];
        allPlayerStats.map((playerName, i) => {
          var onePlayersStats = {
            user: playerName[0].name, value: ranking.makePlayer(playerName[0].ffaSeasonSkill, playerName[0].ffaSeasonRatingDiviation, playerName[0].ffaSeasonVolatility)
          }
          madePlayers.push(onePlayersStats)
        });
        evaluate(madePlayers)
      }
    }

    if (gameType === 'duel') {
      makeTheDuelPlayers();
      function makeTheDuelPlayers() {
        const madePlayers = [];
        allPlayerStats.map((playerName, i) => {
          var onePlayersStats = {
            user: playerName[0].name, value: ranking.makePlayer(playerName[0].duelSkill, playerName[0].duelRatingDiviation, playerName[0].duelVolatility)
          }
          madePlayers.push(onePlayersStats)
        });
        evaluate(madePlayers)
      }

      makeTheDuelSeasonPlayers();
      function makeTheDuelSeasonPlayers() {
        const madePlayers = [];
        allPlayerStats.map((playerName, i) => {
          var onePlayersStats = {
            user: playerName[0].name, value: ranking.makePlayer(playerName[0].duelSeasonSkill, playerName[0].duelSeasonRatingDiviation, playerName[0].duelSeasonVolatility)
          }
          madePlayers.push(onePlayersStats)
        });
        evaluate(madePlayers)
      }
    }

    makeTheCareerPlayers();
    function makeTheCareerPlayers() {
      const madePlayers = [];
      allPlayerStats.map((playerName, i) => {
        var onePlayersStats = {
          user: playerName[0].name, value: ranking.makePlayer(playerName[0].careerSkill, playerName[0].careerRatingDiviation, playerName[0].careerVolatility)
        }
        madePlayers.push(onePlayersStats)
      });
      evaluate(madePlayers)
    }


    function evaluate(madePlayers) {
      let matches = []
      madePlayers.forEach((player, index) => {
        const otherPlayers = madePlayers.slice(index)
        const matchesForPlayer = []
        otherPlayers.forEach(otherPlayer => {
          matchesForPlayer.push([
            player.value,
            otherPlayer.value,
            1
          ])
        })

        matches = [...matches, ...matchesForPlayer]
      })
      console.log('ggggg: ', ranking.getPlayers())
      console.log('this is matches: ', matches)
      ranking.updateRatings(matches)

      return madePlayers.map((playerName, i) => (
        console.log(`${playerName.user} player new rating: ` + madePlayers[i].value.getRating()),
        console.log(`${playerName.user} new rating deviation: ` + madePlayers[i].value.getRd()),
        console.log(`${playerName.user} new volatility: ` + madePlayers[i].value.getVol())
      ));
    }



    console.log('this is updatedStats: ')
  }

  render() {
    return (
      <div>
        <Navbar />
        <div className='banner'>
          <div className='banner-opacity'>
            <h1>Nothing here yet</h1>
          </div>
        </div>
      </div>
    )
  }
}

export default Newsletters;



// const matches = 
// [[player0, player1, 1],
// [player0, player2, 1],
// [player0, player3, 1],
// [player0, player4, 1],
// [player1, player2, 1],
// [player1, player3, 1],
// [player1, player4, 1],
// [player2, player3, 1],
// [player3, player4, 1]]
